name: Debug OIDC Token

on:
  workflow_dispatch:

jobs:
  debug_oidc:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Debug OIDC Request
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Requesting OIDC token"
          echo "Request URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}"
          echo "Request Token length: ${#ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
          echo "Request Token prefix (first 10 chars): ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:0:10}"
          if [ -z "${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}" ]; then
            echo "ERROR: ACTIONS_ID_TOKEN_REQUEST_URL is empty"
            echo "User: $GITHUB_ACTOR - Contact GitHub Support with this log"
            env | grep -i "GITHUB\|ACTIONS" | sort
            exit 1
          fi
