name: Debug OIDC Token

on:
  workflow_dispatch:

jobs:
  debug_oidc:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Debug OIDC Request
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Requesting OIDC token"
          echo "Request URL (secrets): ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}"
          echo "Request URL (env): $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "Request Token length: ${#ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
          echo "Request Token prefix (first 10 chars): ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:0:10}"
          if [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
            echo "ERROR: ACTIONS_ID_TOKEN_REQUEST_URL is empty in env"
            env | grep -i "GITHUB\|ACTIONS" | sort
            exit 1
          fi
          curl -v -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=https://repo.tlle.eu.org/upload" 2>curl_debug.log
          cat curl_debug.log
          oidc_response=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL?audience=https://repo.tlle.eu.org/upload")
          echo "Raw OIDC response: $oidc_response"
          OIDC_TOKEN=$(echo "$oidc_response" | jq -r '.value')
          echo "OIDC Token length: ${#OIDC_TOKEN}"
