name: VyOS LTS with FULLCONENAT Build and Release

permissions:
  contents: write
on:
  push:
    tags:
      - "v1.3*"

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: Asia/Tokyo
      options: --privileged
      

    steps:
    - name: Set env
      run: |
         echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b equuleus --single-branch https://github.com/vyos/vyos-build

   
    - name: Download deb from my server
      run:  |
         set -eux
         cd vyos-build
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/ipset_6.38-1.2_amd64.deb 
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/libipset11_6.38-1.2_amd64.deb
    
    - name: Download kernel deb from my another repo
      uses: robinraju/release-downloader@v1.7
      with:
       repository: "debiansid/vyos-kernel-lts-build"
       tag: "5.4.240"
       fileName: "*.deb"
       out-file-path: "vyos-build/packages/"
       
    - name: Download iptables deb from my another repo
      uses: robinraju/release-downloader@v1.7
      with:
       repository: "debiansid/iptables-fullconenat"
       tag: "debian/1.8.2-4"
       fileName: "*.deb"
       out-file-path: "vyos-build/packages/"     
       
    - name: configure
      working-directory: vyos-build
      run: |
        set -eux
        
        ./configure \
          --architecture amd64 \
          --build-by gpt-5@openai.com \
          --build-type release \
          --custom-package prometheus-node-exporter \
          --version ${{ env.RELEASE_VERSION }}
         
    - name: make iso
      working-directory: vyos-build
      run: |
        set -eux
        
        make iso

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          body: |
            VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true
