name: VyOS LTS with FULLCONENAT Build and Release

permissions:
  contents: write
on:
  push:
    tags:
      - "*FULL*"

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: Asia/Tokyo
      options: --privileged
      

    steps:
    - name: Set env
      run: |
         echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b 1.3.2 --single-branch https://github.com/vyos/vyos-build

   
    - name: Download deb from my server
      run:  |
         set -eux
         cd vyos-build
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/accel-ppp_1.12.0-219-gcc8f2ba_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/iptables_1.8.2-4_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/libip4tc0_1.8.2-4_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/libip6tc0_1.8.2-4_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/libiptc0_1.8.2-4_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/libxtables12_1.8.2-4_amd64.deb  
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/linux-headers-5.4.210-amd64-vyos_5.4.210-1_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/linux-image-5.4.210-amd64-vyos_5.4.210-1_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/linux-tools-5.4.210-amd64-vyos_5.4.210-1_amd64.deb
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/vyos-1x-smoketest_1.3dev0-3790-gb9678136_all.deb  
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/vyos-1x-vmware_1.3dev0-3790-gb9678136_amd64.deb  
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/vyos-1x_1.3dev0-3790-gb9678136_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/vyos-intel-qat_1.7.l.4.9.0-00008-0_amd64.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/vyos-linux-firmware_20230310-22-gbcdcfbc_all.deb 
         wget -P  packages/ http://hnd2.rs4.us/1.3.2/wireguard-dkms_1.0.20210606-1_all.deb 
         
    - name: configure
      working-directory: vyos-build
      run: |
        set -eux
        
        ./configure \
          --architecture amd64 \
          --build-by naa0yama@aoya6i.com \
          --build-type release \
          --custom-package prometheus-node-exporter \
          --version ${{ env.RELEASE_VERSION }}
         
    - name: make iso
      working-directory: vyos-build
      run: |
        set -eux
        
        make iso

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          body: |
            VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true
